name: lint

on:
  workflow_call:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: npm -g install pnpm

      - name: Install Node.js dependencies
        run: cd ./frontend && $npm_package_config_cli install && cd ../backend && $npm_package_config_cli install

      - name: Run linters
        run: cd ./frontend && $npm_package_config_cli run lint && cd ../backend && $npm_package_config_cli run lint
